icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_bg = "#1c1c1c"

[icons]
icons = "material-nf"

[[block]]
block = "net"
interval = 2
format = "^icon_net_up $speed_up.eng(w:3) ^icon_net_down $speed_down.eng(w:3) "

[[block]]
block = "memory"
interval = 5
format = "$icon $mem_used.eng(w:4) "
format_alt = "$icon_swap $swap_used.eng(w:4) "

[[block]]
block = "cpu"
interval = 10
format = "$icon $utilization "

[[block]]
block = "temperature"
format = " $icon $max "
format_alt = "$icon $min min, $max max, $average avg "
good = 20
idle = 50
interval = 10
chip = "*-isa-*"

[[block]]
block = "sound"
format = "^icon_volume {$volume.eng(w:3)|} "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %d/%m %T') "
